### PR TITLE
feat: add merges option for changelog and check command

### PR DESCRIPTION
**Pull request by hdevalke**
Refs: #60, #61, #67

- [x] add option to follow first parent only

### CODE REVIEW

**Comment by ite-klass** [comment]
* Adds `--merges` to check and changelog
* Adds `--simplify-first-parent` to check and changelog

**Comment by ite-klass** [comment]
LGTM, thank you very much! :)

**Comment by ite-klass** [comment]
Help text:

```
       --simplify-first-parent
            Follow only the first parent
```

I think anyone not extensively familiar with git will not understand this. A more elaborate description would be very useful.

Maybe describing the parent system is not necessary, but just “skips merged commits” or something similar to that.

**Comment by ite-klass** [comment]
I’m not sure if `simplify-first-parent` is an adequate description for it?

Isn't it a simlification *to* first parent? Excluding everything despite first parent commits?

So I think the parameter name should be improved; be more specific and correct.

Maybe `--first-parents-only`.

**Comment by ite-klass** [comment]
Not sure if you have a concept or guideline you follow for parameters.

But I would go for something like

* --include-merges
* --first-parents-only

Where include and exclude would be obvious first.

**Comment by hdevalke** [comment]
> I think anyone not extensively familiar with git will not understand this

The concepts of parents is explained in the git book in the [chapter about branching](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell)
I don't think the concept is too hard to understand

**Comment by hdevalke** [comment]
> But I would go for something like
> 
> * `--include-merges`
> * `--first-parents-only` / `--only-first-parents`

I think I will go for `--merges` and `--first-parent` as it seems to be already used on the git cli.

```
❯ cat /usr/share/bash-completion/completions/git | rg -- -- | grep merges\\\|parent
	--first-parent --merges --no-merges
	--min-parents= --max-parents=
	--no-min-parents --no-max-parents
	--simplify-merges --simplify-by-decoration
			--parents --children
			--follow-parent --authors-file= --repack=
			__gitcomp "--revision= --parent"
```

**Pull request merged**
